---

- include_vars:
    dir: vars
    extensions: 
      - yml

- name: Add repositories
  become: yes
  apt_repository:
    repo: "{{ item }}"
  with_items:
    - "{{ repositories }}"

- name: Add Sublime Text apt key
  become: yes
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    install_recommends: yes
  with_items:
    - "{{ packages }}"

- name: Copy scripts
  synchronize: 
    src: files/bin
    dest: "{{ userhome }}"

- name: Custom gconf/dconf settings to prevent gnome desktop starting, and terminal settings
  command: "{{ item }}"
  ignore_errors: True
  with_items:
    - "{{ gconf-commands }}"
  
- name: Copy vim settings
  copy:
    src: files/.vimrc
    dest: "{{ userhome }}/.vimrc"

- name: Copy bashrc settings
  copy:
    src: files/.bashrc
    dest: "{{ userhome }}/.bashrc"

- name: Make sure terminator config directory exists
  file:
    path: "{{ userhome }}/.config/terminator"
    state: directory

- name: Terminator profile
  copy:
    src: files/terminator-config
    dest: "{{ userhome }}/.config/terminator/config"
    force: yes

- name: Clone i3-gaps
  git:
    repo: "https://www.github.com/Airblader/i3"
    dest: "{{ userhome }}/i3-gaps"

- name: Build and install i3-gaps
  become: yes
  chdir: "{{ userhome }}/i3-gaps"
  command: "build-i3gaps.sh"

- name: Template - i3 configuration file
  template:
    dest: "{{ i3_config_directory }}/config"
    src: i3.config.j2
    mode: 0640

- name: Copy i3 files
  synchronize: 
    src: files/.i3
    dest: "{{ userhome }}"

- name: Stop NetworkManager from starting (old way)
  become: yes
  copy:
    content: "manual"
    dest: "/etc/init/network-manager.override"

- name: Stop NetworkManager from starting
  become: yes
  systemd:
    name: "NetworkManager.service"
    state: stopped
    enabled: no

- name: Remove NetworkManager
  become: yes
  apt:
    name: network-manager
    state: absent

...
