---

gconfcommands:
    - "gsettings set org.gnome.desktop.background show-desktop-icons false"
    - "gsettings set org.nemo.desktop show-desktop-icons false"
    - "gsettings set org.gnome.Terminal.Legacy.Settings default-show-menubar false"
    - "gsettings set org.cinnamon.desktop.default-applications.terminal exec 'gnome-terminal'"
    - "gsettings set org.gnome.desktop.default-applications.terminal exec '/usr/bin/gnome-terminal'"

...
