---

i3_config_directory:        "{{ userhome }}/.i3"
i3blocks_config_directory:  "{{ i3_config_directory }}/blocks"
i3blocks_config_file:       "{{ i3blocks_config_directory }}/i3blocks.conf"
compton_config_file:        "{{ i3_config_directory}}/compton/compton.cfg"
i3_mod_key: Mod4

...
