---

packages:
  - sublime-text
  - dconf-gsettings-backend
  - gnome-terminal
  - mesa-utils
  - mesa-utils-extra
  - xorg
  - xserver-xorg-core
  - xserver-xorg
  - nautilus
  - gnome-terminal
  - i3blocks
  - acpi
  - rofi
  - scrot
  - feh
  - imagemagick
  - compton
  - xbacklight
  - alsa-utils
  - tlp
  - xclip
  - vim
  - fonts-inconsolata
  - terminator
  - build-essential
  - libxcb1-dev
  - libxcb-keysyms1-dev
  - libpango1.0-dev
  - libxcb-util0-dev
  - libxcb-icccm4-dev
  - libyajl-dev
  - libstartup-notification0-dev
  - libxcb-randr0-dev
  - libev-dev
  - libxcb-cursor-dev
  - libxcb-xinerama0-dev
  - libxcb-xkb-dev
  - libxkbcommon-dev
  - libxkbcommon-x11-dev
  - libxcb-xrm-dev
  - libxcb-shape0-dev
  - xutils-dev
  - autoconf
  - xterm
  - resolvconf
 #- i3

...
